'use client';

import React, { useEffect, useState, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
    faArrowLeft,
    faSpinner,
    faDownload,
    faPaperPlane,
    faPlus,
    faHistory,
    faBolt,
    faGear,
    faTrash,
    faFileAlt,
    faMessage,
    faTerminal
} from "@fortawesome/free-solid-svg-icons";
import { Instrument_Sans } from "next/font/google";
import { getJob, getFileUrl, Job, getJobEvents, AgentEvent, queryJobMemory, deleteJob, getJobAnalysisResults, AnalysisResult } from '../../../../services/jobs';
import { useJobEvents, ConnectionStatus, ConnectionError } from '../../../../hooks/useJobEvents';
import StepViewer from '../../../../components/StepViewer';
import { GenUI } from '@thesysai/genui-sdk';

const instrument_sans = Instrument_Sans({
    weight: ["400", "500", "600"],
    subsets: ["latin"],
});

// Placeholder markdown content for the documentation panel
const placeholderMarkdown = `
# Job Analysis Report

## Overview
This document provides a comprehensive analysis of the uploaded 3D model, including manufacturing feasibility, material recommendations, and cost estimations.

## Manufacturing Process
**Selected Process:** 3D Printing (FDM)

### Key Considerations
- Layer height optimization for surface finish
- Support structure requirements
- Infill density recommendations

## Material Analysis
| Property | Value |
|----------|-------|
| Material | PLA |
| Density | 1.24 g/cm³ |
| Tensile Strength | 50 MPa |

## Geometry Checks
- ✅ Wall thickness: Adequate (min 1.2mm)
- ✅ Overhangs: Within acceptable range
- ⚠️ Sharp corners detected: Consider filleting

## Cost Estimation
\`\`\`
Material Cost: $12.50
Labor Cost: $8.00
Machine Time: 3.5 hours
-----------------------
Estimated Total: $45.00
\`\`\`

## Recommendations
1. Consider adding fillets to sharp internal corners
2. Orient part for minimal support material
3. Use 20% infill for optimal strength-to-weight ratio

---

*This report was auto-generated by Tactile AI*
`;

export default function JobPage() {
    const params = useParams();
    const router = useRouter();
    const id = params?.id as string;
    const [job, setJob] = useState<Job | null>(null);
    const [loading, setLoading] = useState(true);
    const [initialEventsLoaded, setInitialEventsLoaded] = useState(false);
    const [analysisResult, setAnalysisResult] = useState<AnalysisResult | null>(null);
    const [loadingAnalysis, setLoadingAnalysis] = useState(false);

    // Chat state
    const [messages, setMessages] = useState<{ role: 'user' | 'ai', content: string }[]>([]);
    const [inputValue, setInputValue] = useState('');
    const [isLoading, setIsLoading] = useState(false);

    // View state
    const [activeTab, setActiveTab] = useState<'chat' | 'feed'>('chat');
    const [initialEvents, setInitialEvents] = useState<AgentEvent[]>([]);

    // Settings state
    const [showSettings, setShowSettings] = useState(false);
    const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
    const [isDeleting, setIsDeleting] = useState(false);
    const settingsRef = useRef<HTMLDivElement>(null);

    // Use WebSocket for real-time event streaming
    // Only pass initialEvents once they've been loaded to avoid race condition
    const { events, isConnected, connectionStatus, connectionError } = useJobEvents(
        initialEventsLoaded ? id : null,
        initialEvents
    );

    useEffect(() => {
        if (id) {
            // Load job and initial events in parallel, wait for both
            Promise.all([
                getJob(id),
                getJobEvents(id)
            ]).then(([jobData, eventsData]) => {
                setJob(jobData);
                setInitialEvents(eventsData);
                setInitialEventsLoaded(true);
                setLoading(false);

                // Fetch analysis results if job is completed
                if (jobData && (jobData.status === 'COMPLETED' || jobData.status === 'completed')) {
                    setLoadingAnalysis(true);
                    getJobAnalysisResults(id).then((result) => {
                        setAnalysisResult(result);
                        setLoadingAnalysis(false);
                    }).catch(() => {
                        setLoadingAnalysis(false);
                    });
                }
            }).catch((error) => {
                console.error('Failed to load job data:', error);
                setLoading(false);
            });
        }
    }, [id]);

    // Close settings dropdown when clicking outside
    useEffect(() => {
        const handleClickOutside = (event: MouseEvent) => {
            if (settingsRef.current && !settingsRef.current.contains(event.target as Node)) {
                setShowSettings(false);
            }
        };
        document.addEventListener('mousedown', handleClickOutside);
        return () => document.removeEventListener('mousedown', handleClickOutside);
    }, []);

    const handleDeleteClick = () => {
        setShowDeleteConfirm(true);
        setShowSettings(false);
    };

    const handleConfirmDelete = async () => {
        setIsDeleting(true);
        const success = await deleteJob(id);
        if (success) {
            router.push('/');
        } else {
            setIsDeleting(false);
            setShowDeleteConfirm(false);
        }
    };

    const handleSendMessage = async () => {
        if (!inputValue.trim() || isLoading) return;

        const userMessage = inputValue.trim();
        setMessages(prev => [...prev, { role: 'user', content: userMessage }]);
        setInputValue('');
        setIsLoading(true);

        try {
            const response = await queryJobMemory(id, userMessage);
            if (response) {
                setMessages(prev => [...prev, {
                    role: 'ai',
                    content: response.answer + (response.sourcesUsed > 0 ? `\n\n📚 Based on ${response.sourcesUsed} source${response.sourcesUsed > 1 ? 's' : ''} from the analysis.` : '')
                }]);
            } else {
                setMessages(prev => [...prev, {
                    role: 'ai',
                    content: "Sorry, I couldn't process your question. Please try again."
                }]);
            }
        } catch (error) {
            console.error("Chat error:", error);
            setMessages(prev => [...prev, {
                role: 'ai',
                content: "An error occurred while processing your question."
            }]);
        } finally {
            setIsLoading(false);
        }
    };

    if (loading) {
        return (
            <div className="w-full h-full flex flex-col items-center justify-center bg-zinc-50 gap-4">
                <div className="relative w-12 h-12">
                    <div className="absolute inset-0 border-4 border-zinc-200 rounded-full"></div>
                    <div className="absolute inset-0 border-4 border-t-primary border-r-transparent border-b-transparent border-l-transparent rounded-full animate-spin"></div>
                </div>
            </div>
        );
    }

    if (!job) {
        return (
            <div className="flex flex-col items-center justify-center w-full h-full gap-4 p-12 bg-zinc-50">
                <p className="text-zinc-500">Job not found.</p>
                <Link href="/" className="text-primary hover:underline">Go back home</Link>
            </div>
        );
    }

    return (
        <div className="flex flex-col w-full h-full overflow-hidden bg-zinc-50">
            {/* Delete Confirmation Modal */}
            {showDeleteConfirm && (
                <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
                    <div className="bg-white border border-zinc-200 shadow-xl p-6 max-w-sm w-full mx-4">
                        <h3 className={`text-lg font-semibold text-zinc-900 mb-2 ${instrument_sans.className}`}>Delete Job?</h3>
                        <p className="text-sm text-zinc-500 mb-6">This action cannot be undone. The job and all associated data will be permanently deleted.</p>
                        <div className="flex gap-3 justify-end">
                            <button
                                onClick={() => setShowDeleteConfirm(false)}
                                disabled={isDeleting}
                                className="px-4 py-2 text-sm font-medium text-zinc-600 bg-zinc-100 border border-zinc-200 hover:bg-zinc-200 transition-colors cursor-pointer disabled:opacity-50"
                            >
                                Cancel
                            </button>
                            <button
                                onClick={handleConfirmDelete}
                                disabled={isDeleting}
                                className="px-4 py-2 text-sm font-medium text-white bg-red-500 border border-red-500 hover:bg-red-600 transition-colors cursor-pointer flex items-center gap-2 disabled:opacity-50"
                            >
                                {isDeleting ? (
                                    <>
                                        <FontAwesomeIcon icon={faSpinner} className="animate-spin" />
                                        Deleting...
                                    </>
                                ) : (
                                    <>
                                        <FontAwesomeIcon icon={faTrash} />
                                        Delete
                                    </>
                                )}
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {/* Top Bar / Data Nav */}
            <div className={`h-13.5 border-b border-zinc-200 bg-white flex items-center justify-between px-6 shrink-0 z-20 ${instrument_sans.className}`}>
                <div className="flex items-center gap-4 overflow-hidden">
                    <Link href="/" className="flex items-center justify-center w-8 h-8 hover:bg-zinc-100 text-zinc-500 transition-colors">
                        <FontAwesomeIcon icon={faArrowLeft} className="text-sm" />
                    </Link>

                    <div className="h-6 w-px bg-zinc-200 mx-2 hidden md:block"></div>

                    <div className="flex flex-col">
                        <h1 className="text-sm font-semibold text-zinc-900 truncate max-w-[200px]">{job.originalFilename}</h1>
                        <span className="text-[10px] text-zinc-500 font-mono">{job.id}</span>
                    </div>

                    <div className="hidden md:flex items-center gap-4 ml-6">
                        <div className="flex flex-col">
                            <span className="text-[10px] uppercase text-zinc-400 font-bold tracking-wider">Status</span>
                            <span className="text-xs font-medium text-zinc-700 capitalize">{job.status.replace('_', ' ')}</span>
                        </div>
                        <div className="flex flex-col">
                            <span className="text-[10px] uppercase text-zinc-400 font-bold tracking-wider">Process</span>
                            <span className="text-xs font-medium text-zinc-700">{job.manufacturingProcess}</span>
                        </div>
                        <div className="flex flex-col">
                            <span className="text-[10px] uppercase text-zinc-400 font-bold tracking-wider">Material</span>
                            <span className="text-xs font-medium text-zinc-700">PLA</span>
                        </div>
                    </div>
                </div>

                <div className="flex items-center gap-2">
                    <a
                        href={getFileUrl(job.fileStorageId)}
                        className="bg-zinc-100 text-zinc-700 px-3 py-1.5 text-xs font-medium hover:bg-zinc-200 transition-colors flex items-center gap-2 border border-zinc-200"
                        download
                    >
                        <FontAwesomeIcon icon={faDownload} />
                        Download
                    </a>

                    {/* Settings Dropdown */}
                    <div className="relative" ref={settingsRef}>
                        <button
                            onClick={() => setShowSettings(!showSettings)}
                            className="w-8 h-8 flex items-center justify-center text-zinc-500 hover:text-zinc-800 hover:bg-zinc-100 border border-zinc-200 transition-colors cursor-pointer"
                            title="Settings"
                        >
                            <FontAwesomeIcon icon={faGear} className="text-sm" />
                        </button>

                        {showSettings && (
                            <div className="absolute right-0 top-full mt-1 bg-white border border-zinc-200 shadow-lg z-50 min-w-[160px]">
                                <button
                                    onClick={handleDeleteClick}
                                    className="w-full px-4 py-2.5 text-left text-sm text-red-600 hover:bg-red-50 flex items-center gap-3 transition-colors cursor-pointer"
                                >
                                    <FontAwesomeIcon icon={faTrash} className="text-xs" />
                                    Delete Job
                                </button>
                            </div>
                        )}
                    </div>
                </div>
            </div>

            {/* Main Content Area */}
            <div className="flex-1 flex flex-col overflow-hidden">

                {/* Top Half: 1/2 Width Render + 1/2 Width Markdown */}
                <div className="h-1/2 overflow-hidden flex border-b border-zinc-200">
                    {/* Left: 3D Render */}
                    <div className="w-1/2 bg-zinc-900 relative">
                        {job.fileStorageId ? (
                            <StepViewer url={getFileUrl(job.fileStorageId)} />
                        ) : (
                            <div className="w-full h-full flex items-center justify-center text-zinc-500">
                                No Model Data
                            </div>
                        )}
                    </div>

                    {/* Right: Analysis Report */}
                    <div className="w-1/2 bg-white flex flex-col border-l border-zinc-200">
                        <div className="h-10 border-b border-zinc-100 flex items-center justify-between px-4 bg-zinc-50 shrink-0">
                            <div className="flex items-center gap-2">
                                <FontAwesomeIcon icon={faFileAlt} className="text-zinc-400 text-xs" />
                                <span className="text-[11px] font-semibold text-zinc-600 uppercase tracking-wider">Analysis Report</span>
                            </div>
                            <span className="text-[10px] text-zinc-400 font-mono">
                                {analysisResult?.c1UiReport ? 'ai-generated' : 'analysis.md'}
                            </span>
                        </div>
                        <div className="flex-1 overflow-y-auto p-8">
                            {loadingAnalysis ? (
                                <div className="flex items-center justify-center h-full">
                                    <div className="flex items-center gap-3">
                                        <FontAwesomeIcon icon={faSpinner} className="animate-spin text-primary" />
                                        <span className="text-sm text-zinc-500">Loading analysis...</span>
                                    </div>
                                </div>
                            ) : analysisResult?.c1UiReport ? (
                                <GenUI content={analysisResult.c1UiReport} />
                            ) : analysisResult?.markdownReport ? (
                                <div className="prose prose-sm prose-zinc max-w-none
                                    prose-headings:text-zinc-900 prose-headings:font-bold
                                    prose-h1:text-xl prose-h1:mb-6 prose-h1:pb-2 prose-h1:border-b prose-h1:border-zinc-100
                                    prose-h2:text-sm prose-h2:uppercase prose-h2:tracking-wider prose-h2:text-zinc-500 prose-h2:mt-8 prose-h2:mb-4
                                    prose-p:text-zinc-600 prose-p:leading-relaxed
                                    prose-table:border prose-table:border-zinc-100 prose-table:rounded-lg prose-table:overflow-hidden
                                    prose-thead:bg-zinc-50 prose-th:px-4 prose-th:py-2 prose-th:text-zinc-700
                                    prose-td:px-4 prose-td:py-2 prose-td:border-t prose-td:border-zinc-50
                                    prose-code:bg-zinc-100 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-code:text-zinc-800
                                    prose-pre:bg-zinc-900 prose-pre:text-zinc-100 prose-pre:p-4 prose-pre:rounded-none
                                ">
                                    <ReactMarkdown>{analysisResult.markdownReport}</ReactMarkdown>
                                </div>
                            ) : (
                                <div className="prose prose-sm prose-zinc max-w-none
                                    prose-headings:text-zinc-900 prose-headings:font-bold
                                    prose-h1:text-xl prose-h1:mb-6 prose-h1:pb-2 prose-h1:border-b prose-h1:border-zinc-100
                                    prose-h2:text-sm prose-h2:uppercase prose-h2:tracking-wider prose-h2:text-zinc-500 prose-h2:mt-8 prose-h2:mb-4
                                    prose-p:text-zinc-600 prose-p:leading-relaxed
                                    prose-table:border prose-table:border-zinc-100 prose-table:rounded-lg prose-table:overflow-hidden
                                    prose-thead:bg-zinc-50 prose-th:px-4 prose-th:py-2 prose-th:text-zinc-700
                                    prose-td:px-4 prose-td:py-2 prose-td:border-t prose-td:border-zinc-50
                                    prose-code:bg-zinc-100 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-code:text-zinc-800
                                    prose-pre:bg-zinc-900 prose-pre:text-zinc-100 prose-pre:p-4 prose-pre:rounded-none
                                ">
                                    <ReactMarkdown>{placeholderMarkdown}</ReactMarkdown>
                                </div>
                            )}
                        </div>
                    </div>
                </div>

                {/* Bottom Half: AI Chat + Live Events (Full Width) */}
                <div className="h-1/2 flex flex-col bg-white">
                    {/* Console-style Tabs Divider */}
                    <div className="h-11 border-b border-zinc-200 flex items-center justify-between px-6 bg-white shrink-0">
                        <div className="flex items-center gap-2 h-full">
                            <button
                                onClick={() => setActiveTab('chat')}
                                className={`h-full px-4 flex items-center gap-2 text-xs font-semibold transition-all border-b-2 ${activeTab === 'chat'
                                    ? 'border-zinc-900 text-zinc-900'
                                    : 'border-transparent text-zinc-400 hover:text-zinc-600 cursor-pointer'
                                    }`}
                            >
                                <FontAwesomeIcon icon={faMessage} className="text-[10px]" />
                                AI Assistant
                            </button>
                            <button
                                onClick={() => setActiveTab('feed')}
                                className={`h-full px-4 flex items-center gap-2 text-xs font-semibold transition-all border-b-2 ${activeTab === 'feed'
                                    ? 'border-primary text-primary'
                                    : 'border-transparent text-zinc-400 hover:text-zinc-600 cursor-pointer'
                                    }`}
                            >
                                <FontAwesomeIcon icon={faTerminal} className="text-[10px]" />
                                Live Agent Feed
                                <span className={`flex items-center gap-1.5 ml-2 px-1.5 py-0.5 bg-zinc-100 rounded text-[9px] ${isConnected ? 'text-green-600' : 'text-zinc-400'}`}>
                                    <span className={`w-1.5 h-1.5 rounded-full ${isConnected ? 'bg-green-500 animate-pulse' : 'bg-zinc-300'}`}></span>
                                    {isConnected ? 'LIVE' : 'OFFLINE'}
                                </span>
                            </button>
                        </div>

                        <div className="flex items-center gap-4">
                            {activeTab === 'chat' && (
                                <div className="flex items-center gap-1">
                                    <button className="p-2 text-zinc-400 hover:text-zinc-900 transition-colors cursor-pointer" title="Chat History">
                                        <FontAwesomeIcon icon={faHistory} className="text-xs" />
                                    </button>
                                    <button
                                        onClick={() => setMessages([])}
                                        className="p-2 text-zinc-400 hover:text-zinc-900 transition-colors cursor-pointer"
                                        title="New Discussion"
                                    >
                                        <FontAwesomeIcon icon={faPlus} className="text-xs" />
                                    </button>
                                </div>
                            )}
                            <div className="h-4 w-px bg-zinc-200"></div>
                            <button className="text-[10px] font-mono text-zinc-400 hover:text-zinc-600 transition-colors">
                                CMD + ? FOR HELP
                            </button>
                        </div>
                    </div>

                    {/* Full Width Content Content */}
                    <div className="flex-1 overflow-hidden flex bg-zinc-50/20">
                        {activeTab === 'chat' ? (
                            <div className="flex-1 flex flex-col max-w-5xl mx-auto w-full">
                                {messages.length === 0 ? (
                                    <div className="flex flex-col items-center justify-center p-12 text-center">
                                        <div className="flex flex-wrap gap-2 justify-center">
                                            <button className="px-3 py-1.5 bg-white border border-zinc-200 text-zinc-600 text-[11px] rounded hover:border-zinc-400 transition-all cursor-pointer">
                                                How heavy is this part in Aluminum?
                                            </button>
                                            <button className="px-3 py-1.5 bg-white border border-zinc-200 text-zinc-600 text-[11px] rounded hover:border-zinc-400 transition-all cursor-pointer">
                                                Check minimum wall thickness
                                            </button>
                                            <button className="px-3 py-1.5 bg-white border border-zinc-200 text-zinc-600 text-[11px] rounded hover:border-zinc-400 transition-all cursor-pointer">
                                                Estimate print time at 200μm
                                            </button>
                                        </div>
                                    </div>
                                ) : (
                                    <div className="flex-1 overflow-y-auto p-6 flex flex-col gap-6">
                                        {messages.map((msg, idx) => (
                                            <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                                                <div className={`max-w-[80%] rounded-xl p-4 ${msg.role === 'user'
                                                    ? 'bg-zinc-900 text-white'
                                                    : 'bg-white border border-zinc-200 text-zinc-800'
                                                    }`}>
                                                    <div className="text-[10px] font-bold uppercase tracking-widest mb-1 opacity-50">
                                                        {msg.role === 'user' ? 'You' : 'Tactile AI'}
                                                    </div>
                                                    {msg.role === 'ai' ? (
                                                        <div className="text-sm leading-relaxed prose prose-sm prose-zinc max-w-none prose-invert-0">
                                                            <ReactMarkdown>{msg.content}</ReactMarkdown>
                                                        </div>
                                                    ) : (
                                                        <div className="text-sm leading-relaxed whitespace-pre-wrap">
                                                            {msg.content}
                                                        </div>
                                                    )}
                                                </div>
                                            </div>
                                        ))}
                                        {isLoading && (
                                            <div className="flex justify-start">
                                                <div className="bg-white border border-zinc-200 rounded-xl p-4 flex items-center gap-3">
                                                    <FontAwesomeIcon icon={faSpinner} className="animate-spin text-primary text-xs" />
                                                    <span className="text-xs text-zinc-500 font-medium">Processing request...</span>
                                                </div>
                                            </div>
                                        )}
                                        <div className="h-4 shrink-0"></div>
                                    </div>
                                )}

                                <div className="p-6 bg-transparent">
                                    <div className="relative group max-w-3xl mx-auto">
                                        <div className="absolute -inset-0.5 blur opacity-50 group-focus-within:opacity-100 transition duration-500"></div>
                                        <div className="relative flex flex-col border border-zinc-200 bg-white focus-within:border-zinc-400 transition-all duration-200">
                                            <input
                                                type="text"
                                                className="w-full bg-transparent text-sm p-4 focus:outline-none placeholder:text-zinc-400"
                                                placeholder={isLoading ? "AI is thinking..." : "Ask a technical follow-up..."}
                                                value={inputValue}
                                                onChange={(e) => setInputValue(e.target.value)}
                                                onKeyDown={(e) => e.key === 'Enter' && handleSendMessage()}
                                                disabled={isLoading}
                                            />
                                            <div className="flex justify-between items-center px-4 pb-3">
                                                <div className="flex gap-2">
                                                    <span className="px-1.5 py-0.5 rounded bg-zinc-100 text-[9px] font-mono text-zinc-500 uppercase tracking-tighter">Enter to send</span>
                                                    <span className="px-1.5 py-0.5 rounded bg-zinc-100 text-[9px] font-mono text-zinc-500 uppercase tracking-tighter">Markdown supported</span>
                                                </div>
                                                <button
                                                    onClick={handleSendMessage}
                                                    disabled={isLoading}
                                                    className={`h-10 w-10 transition-all flex items-center justify-center ${isLoading
                                                        ? 'text-zinc-300'
                                                        : 'text-zinc-100 bg-zinc-900 hover:bg-black cursor-pointer'
                                                        }`}
                                                >
                                                    <FontAwesomeIcon icon={faPaperPlane} className="text-[10px]" />
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        ) : (
                            /* Live Feed View - Redesigned for wide layout */
                            <div className="flex-1 overflow-y-auto p-6 font-mono">
                                <div className="max-w-6xl mx-auto flex flex-col gap-1">
                                    {events.length === 0 ? (
                                        <div className="flex flex-col items-center justify-center p-20 text-zinc-300">
                                            <FontAwesomeIcon icon={faBolt} className="text-4xl mb-4 opacity-20" />
                                            <span className="text-[10px] font-bold tracking-[0.2em] uppercase">No events logged</span>
                                        </div>
                                    ) : (
                                        events.map((event) => (
                                            <div key={event.id} className="flex gap-4 py-2 px-3 border-b border-zinc-100/50 hover:bg-zinc-100/50 transition-colors group">
                                                <span className="text-[10px] text-zinc-400 shrink-0 w-20 pt-0.5">
                                                    [{new Date(event.createdAt).toLocaleTimeString([], { hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit' })}]
                                                </span>
                                                <div className="flex flex-col flex-1 min-w-0">
                                                    <div className="flex items-center gap-2">
                                                        <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded ${event.type === 'ERROR' ? 'bg-red-50 text-red-500' :
                                                            event.type === 'SUCCESS' ? 'bg-green-50 text-green-600' :
                                                                event.type === 'THINKING' ? 'bg-yellow-50 text-yellow-600' :
                                                                    'bg-blue-50 text-blue-600'
                                                            }`}>
                                                            {event.type}
                                                        </span>
                                                        <span className="text-[11px] font-bold text-zinc-700 truncate">{event.title}</span>
                                                    </div>
                                                    {event.content && (
                                                        <p className="text-[11px] text-zinc-500 mt-1 pl-0 whitespace-pre-wrap leading-relaxed opacity-80 group-hover:opacity-100">
                                                            {event.content}
                                                        </p>
                                                    )}
                                                </div>
                                                <div className="shrink-0 pt-0.5">
                                                    <div className={`w-1.5 h-1.5 rounded-full ${event.type === 'ERROR' ? 'bg-red-500' :
                                                        event.type === 'SUCCESS' ? 'bg-green-500' :
                                                            event.type === 'THINKING' ? 'bg-yellow-400 animate-pulse' :
                                                                'bg-blue-500'
                                                        }`}></div>
                                                </div>
                                            </div>
                                        ))
                                    )}
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}
