"""
Report generator for DFM analysis results.
Creates markdown output for display.
"""

from typing import List, Optional
from models import Issue, Suggestion, GeometrySummary, Severity


def generate_markdown_report(
    issues: List[Issue],
    suggestions: List[Suggestion],
    geometry_summary: Optional[GeometrySummary] = None,
    manufacturing_process: str = "Unknown"
) -> str:
    """
    Generate a formatted markdown report from analysis results.
    
    Args:
        issues: List of detected DFM issues
        suggestions: List of fix suggestions
        geometry_summary: Optional geometry info
        manufacturing_process: The manufacturing process analyzed for
        
    Returns:
        Formatted markdown string
    """
    
    lines = [
        "# DFM Analysis Report",
        "",
        f"**Manufacturing Process:** {manufacturing_process.replace('_', ' ').title()}",
        "",
    ]
    
    # Geometry Summary Section
    if geometry_summary:
        lines.extend([
            "## Geometry Summary",
            "",
            "| Property | Value |",
            "|----------|-------|",
            f"| Face Count | {geometry_summary.face_count} |",
            f"| Edge Count | {geometry_summary.edge_count} |",
        ])
        if geometry_summary.volume:
            lines.append(f"| Volume | {geometry_summary.volume:.2f} mm³ |")
        if geometry_summary.surface_area:
            lines.append(f"| Surface Area | {geometry_summary.surface_area:.2f} mm² |")
        lines.append("")
    
    # Issues Summary
    error_count = sum(1 for i in issues if i.severity == Severity.ERROR)
    warning_count = sum(1 for i in issues if i.severity == Severity.WARNING)
    info_count = sum(1 for i in issues if i.severity == Severity.INFO)
    
    lines.extend([
        "## Issues Summary",
        "",
        f"- 🔴 **Errors:** {error_count}",
        f"- 🟡 **Warnings:** {warning_count}",
        f"- 🔵 **Info:** {info_count}",
        "",
    ])
    
    # Detailed Issues
    if issues:
        lines.extend([
            "## Issues Detected",
            "",
        ])
        
        for i, issue in enumerate(issues, 1):
            severity_icon = {"ERROR": "🔴", "WARNING": "🟡", "INFO": "🔵"}.get(
                issue.severity.value, "⚪"
            )
            
            lines.extend([
                f"### {i}. {severity_icon} {issue.rule_name}",
                "",
                f"**Rule ID:** `{issue.rule_id}`  ",
                f"**Severity:** {issue.severity.value}",
                "",
                issue.description,
                "",
            ])
            
            if issue.affected_features:
                lines.append(f"**Affected Features:** {', '.join(issue.affected_features)}")
                lines.append("")
            
            lines.extend([
                f"> **Recommendation:** {issue.recommendation}",
                "",
            ])
            
            if issue.auto_fix_available:
                lines.append("✅ *Auto-fix available*")
                lines.append("")
    
    # Suggestions with Code
    if suggestions:
        lines.extend([
            "## Fix Suggestions",
            "",
        ])
        
        for i, suggestion in enumerate(suggestions, 1):
            lines.extend([
                f"### Fix {i}: {suggestion.description}",
                "",
                f"**Priority:** {'⭐' * suggestion.priority}  ",
                f"**Expected Improvement:** {suggestion.expected_improvement}",
                "",
            ])
            
            if suggestion.code_snippet:
                lines.extend([
                    "```python",
                    suggestion.code_snippet,
                    "```",
                    "",
                ])
            
            if suggestion.validated:
                lines.append("✅ *Validated - produces valid geometry*")
            else:
                lines.append("⚠️ *Not validated - review before applying*")
            lines.append("")
    
    # Footer
    lines.extend([
        "---",
        "",
        "*Generated by Tactile DFM Analyzer*",
    ])
    
    return "\n".join(lines)
